-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 03:22:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gerenciador_mercado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gerenciador_mercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gerenciador_mercado` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gerenciador_mercado` ;

-- -----------------------------------------------------
-- Table `gerenciador_mercado`.`residencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciador_mercado`.`residencias` (
  `id_residencia` INT NOT NULL AUTO_INCREMENT,
  `usuario_adm_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_residencia`),
  INDEX `fk_residencias_usuarios1_idx` (`usuario_adm_id` ASC) VISIBLE,
  CONSTRAINT `fk_residencias_usuarios1`
    FOREIGN KEY (`usuario_adm_id`)
    REFERENCES `gerenciador_mercado`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2000
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gerenciador_mercado`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciador_mercado`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `residencia_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_residencias_idx` (`residencia_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_residencias`
    FOREIGN KEY (`residencia_id`)
    REFERENCES `gerenciador_mercado`.`residencias` (`id_residencia`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1000
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `gerenciador_mercado`.`produtos_residencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciador_mercado`.`produtos_residencia` (
  `id_produto_residencia` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `quantidade_unid` INT NULL DEFAULT NULL,
  `unidade_de_medida` ENUM('kg', 'g', 'l', 'ml') NULL DEFAULT NULL,
  `categoria` VARCHAR(20) NULL DEFAULT NULL,
  `preco_medio` FLOAT NULL DEFAULT NULL,
  `residencia_id` INT NOT NULL,
  `quantidade_existente` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_produto_residencia`),
  INDEX `fk_produtos_residencia_residencias1_idx` (`residencia_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_residencia_residencias1`
    FOREIGN KEY (`residencia_id`)
    REFERENCES `gerenciador_mercado`.`residencias` (`id_residencia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4000
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gerenciador_mercado`.`produtos_listados_pessoais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciador_mercado`.`produtos_listados_pessoais` (
  `quantidade_listada` INT NOT NULL,
  `produto_residencia_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`produto_residencia_id`, `usuario_id`),
  INDEX `fk_produtos_listados_pessoais_produtos_residencia1_idx` (`produto_residencia_id` ASC) VISIBLE,
  INDEX `fk_produtos_listados_pessoais_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_listados_pessoais_produtos_residencia1`
    FOREIGN KEY (`produto_residencia_id`)
    REFERENCES `gerenciador_mercado`.`produtos_residencia` (`id_produto_residencia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produtos_listados_pessoais_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gerenciador_mercado`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gerenciador_mercado`.`transferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciador_mercado`.`transferencias` (
  `id_transferencia` INT NOT NULL AUTO_INCREMENT,
  `confirmado` TINYINT(1) NOT NULL,
  `beneficiado_id` INT NOT NULL,
  `pagador_id` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id_transferencia`),
  INDEX `fk_transferencias_usuarios1_idx` (`beneficiado_id` ASC) VISIBLE,
  INDEX `fk_transferencias_usuarios2_idx` (`pagador_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 6000
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
